spring:
  profiles:
    active: cloud

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
  endpoint:
    info:
      enabled: true
    health:
      enabled: true

inboundgateway:
  backend:
    product:
      queue: products.manage.queue